### ISSUE TITLE
Unable to upload to App Store Connect

### ISSUE THREAD

**Issue by loganblevins** [OneSignal/OneSignal-XCFramework#10]
Error with Xcode Version 12.4 (12D4e):

`The bundle Payload/Covenant Eyes.app/PlugIns/OneSignal.framework is not contained in a correctly named directory. It should be under "Frameworks".".
`

Issue is resolved by hand, deleting framework from PlugIns.

https://forums.swift.org/t/swift-package-binary-framework-issue/41922 

However, OneSignal is the only troublesome SPM package I've encountered - and we use multiple SPM packages.

Is there anything OneSignal can do to resolve this?

**Comment by loganblevins** [comment]
We have had to revert back to the standard framework package to avoid this bug. 

This XCFramework is quite literally unusable as-is. Our automated builders are failing to upload to App Store Connect and we cannot rely on developers deleting a duplicate framework within an archive to make the upload succeed.

**Comment by blorsch** [comment]
We are also experiencing this issue. After adding via SPM OneSignal works perfectly and can be archived, but when we go to upload to App Store Connect we receive a whole slew of errors:
<img width="402" alt="Screen Shot 2021-03-21 at 10 58 12 PM" src="https://user-images.githubusercontent.com/11636145/112073861-23316f00-8b32-11eb-97db-8f5d4b342a88.png">
<img width="409" alt="Screen Shot 2021-03-21 at 11 04 26 PM" src="https://user-images.githubusercontent.com/11636145/112073865-24fb3280-8b32-11eb-8743-d00953e7ae27.png">

If I inspect the .app file, it looks like OneSignal.framework and the notification app extension are being placed within the  "PlugIns" folder, erroneously according to Xcode. We have other SPM packages and we’ve been able to successfully upload builds for months with them. We are planning to use OneSignal in production, but we can’t until we can upload builds.

Any help would be much appreciated. This is with OneSignal-XCFramework v3.3.0 and Xcode 12.4.

**Comment by josala** [comment]
I had the same issue and I had to remove the OneSignal Swift package and install it via pod. Make sure to specify the latest version (currently pod 'OneSignal', '3.4.0') because otherwise installs 2.x and has some incompatibilities with the current SDK setup guide.

**Comment by zoejessica** [comment]
We are running into exactly the same issue - we were able to resolve (on CI too) by adding a final build phase script that removes the OneSignal framework from the Plugins folder, as per [this technique by Kevin Bui](https://forums.swift.org/t/swift-package-binary-framework-issue/41922/3). `$(BUILT_PRODUCTS_DIR)/$(PLUGINS_FOLDER_PATH)/OneSignal.framework` needs to be added as an Input File for the script.

**Comment by salami** [comment]
Same problem here. Using OneSignal-XCFramework SPM on an M1 Apple Silicon Mac. Xcode 12.5

I just switched over to OneSignal-iOS-SDK for now, still using SPM. Please address this, thank you.

**Comment by acoomans** [comment]
+1 same issue here. Would like to see this solved.

**Comment by emawby** [comment]
Thank you for reporting I am looking into this. It seems like other Binary Swift Packages are [having similar issues ](https://forums.swift.org/t/swift-package-binary-framework-issue/41922/9). I was hopeful that Xcode 12.5 would solve the issue, but it seems it hasn't. 

To be clear are folks having issues archiving their apps or is there only an issue occurring once the archive has been uploaded to App Store connect?

**Comment by salami** [comment]
The archive is successful. The error occurs at the end of the upload process and it does not get sent to App Store Connect.

**Comment by emawby** [comment]
I am able to reproduce this. I get the same errors as when I include the XCFramework directly and embed it both the App and Extension targets. I am not sure why SwiftPM is trying to embed the framework when it doesn't need to. I will look into ways to modify the Package itself to make it not do that, but otherwise we will need a build script to fix the issue until Apple addresses it. I apologize for the inconvenience.

**Comment by imrealashu** [comment]
@emawby I've been facing the same issue and ended up here and did the steps you've mentioned. It solved two of the errors, thanks for that but, this still has 2 issues. Could you help me point out what are those?
I'm using React Native (`>0.60`) with OneSignal. 
![Screenshot 2021-06-13 at 03 35 21](https://user-images.githubusercontent.com/3916999/121790037-d0c79200-cbf8-11eb-9f00-1e4600da222e.png)

Thanks in advance!

**Comment by emawby** [comment]
@imrealashu What version of React-Native-OneSignal are you using?

**Comment by emawby** [comment]
Updating with another workaround. Instead of directly including the OneSignal library in the NotificationServiceExtension target you can update the NSE's `Runpath search paths` build setting to include the path `@executable_path/../../Frameworks`. This will make it so that the NSE will look for Frameworks in the main app targets Frameworks directory.
![image](https://user-images.githubusercontent.com/13123372/123854824-07c5c500-d8d4-11eb-97d6-a57070494785.png)

**Comment by neha275** [comment]
+1 facing same issue
can anybody resolved this?

**Comment by Semty** [comment]
@neha275 confirmed, it's still here
@emawby when will this issue be fixed? Your second 'workaround' just doesn't work, the first one works, but it feels just wrong

**Comment by ispiropoulos** [comment]
@Semty the second "work around" was actually set by default on a project I am working. I was facing a different problem but triggered by the same root cause (Xcode was crashing at archive export), and it seems like adding the framework into the notification extension target is redundant, at least with Xcode 13.1 as it automatically configures Runpath Search Paths like @emawby described above.

**Comment by cdf1982** [comment]
@emawby's [workaround 1](https://github.com/OneSignal/OneSignal-XCFramework/issues/10#issuecomment-845480579) is still useful: with **Xcode 13.1** and **OneSignalXCFramework 3.9.1** I could archive successfully, but as soon as I started the signing process in an Ad Hoc distribution, Xcode would actually crash!

**Removing the folder as recommended fixed the crash and therefore the issue**.

Hopefully, an actual solution that not requires spelunking in the package will be available with a future release.

**Comment by paskcountry** [comment]
Still same issue, I solved the problem with the workaround 1. Thanks @emawby ! .But not sure if it would not affect  the behaviour of OneSignal Notifications. I am not able to deliver the notifications to all users (who has accept the push notifications of course). I am using SPM.

**Comment by emawby** [comment]
@paskcountry Hello I am sorry to hear about the issue with notification delivery. This issue should not be affecting that so if you are still having issues feel free to open a new issue on the [iOS SDK repo](https://github.com/OneSignal/OneSignal-iOS-SDK).

**Comment by paskcountry** [comment]
Thanks for your reply emawby! I have integrated OneSignal in another app. And It's working fine. There's one step to integrate it that I have avoid this time. In the documentation page, to integrate it via Swift Package Manager (I love SPM) [](https://documentation.onesignal.com/docs/swift-package-manager-setup) . STEP 6 : 6_**. Select the OneSignalNotificationServiceExtension (follow the setup guide if you have not created one yet) and under "Frameworks and Libraries" click the + button.**_ I have not do it this time. 

So no need to after archiving it, doing these steps, you told before:

 Right click the Archive
Show in finder
Right click > Show package contents of the .xcarchive
Products > Applications > xx.app > Right click Show package contents
Plugins > OneSignalNotificationServiceExtension.appex > Right click Show package contents
Delete the Frameworks folder.

The upload to the app store was successful and Notifications working really WELL.

**Comment by mmonikas** [comment]
@emawby are those workarounds you described the only solution to the problem currently? The second one does not work for me and the first one seems to be problematic when using CI. Can we expect that the issues will be fixed somehow by OneSignal in the future?

**Comment by emawby** [comment]
Great that is good to know I will remove that line from the documentation

**Comment by LukaszDziwosz** [comment]
How to attach keys with SMP?

**Comment by raphaeldcout** [comment]
Hello,
i'm experiencing this problem. Any permanent solution?

**Comment by jarrodparkes** [comment]
I'm still experiencing the same problem (`CFBundleCollision`) when trying to build with Bitrise CI/CD's most recent, stable stack — Xcode 13.2.x on macOS 11.6 (Big Sur).

**Comment by mortenholmgaard** [comment]
@emawby Please look into this issue! We have all kinds of problems with this with every release we are trying to build!!

**Comment by mortenholmgaard** [comment]
I didn't get this problem the first time I tried in xCode 13.3 - any one else that can verify if this is solved in that version?

**Comment by paolosanchi** [comment]
I solved with installing the framework with the CocoaPod (Option 3) instead of  using the Swift Package Manager (Option 1).
https://documentation.onesignal.com/docs/ios-sdk-setup#step-3-import-the-onesignal-sdk-into-your-xcode-project

**Comment by marister** [comment]
We solved it by telling the library not to embed Swift libraries. Hope it helps someone.
![image](https://user-images.githubusercontent.com/1228519/166529497-d7704277-5c8d-4537-a1cf-79c3083b4731.png)

**Comment by AlexHartford** [comment]
This is still an issue regardless of how the extension or app is configured.

Using https://github.com/OneSignal/OneSignal-iOS-SDK instead works ([Make sure to use at least this version and follow the instructions!](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/3.11.0)) - but this issue needs to be addressed as the documentation for SPM is recommending this version of OneSignal.

It appears that the build I linked was actually created to solve this issue, but for some reason, there is no reference to it in this repository or the documentation.

**Comment by UraFIZ** [comment]
> What do you mean by saying 'otherwise installs 2.x '?

**Comment by phanbaohuy96** [comment]
> We solved it in our React Native project by telling the library not to embed Swift libraries. Hope it helps someone. (We use cocopods)
> 
> ![image](https://user-images.githubusercontent.com/1228519/166529497-d7704277-5c8d-4537-a1cf-79c3083b4731.png)

This saves my day! Tks you.

**Comment by Senninseyi** [comment]
<img width="841" alt="Screenshot 2024-07-11 at 09 06 45" src="https://github.com/OneSignal/OneSignal-XCFramework/assets/25735313/779d9c15-e4bf-4748-be95-4d2814601bae">

This is the issue i face when i try to push to appstore

**Comment by nan-li** [comment]
Closing due to inactivity and staleness. @Senninseyi your error is related to your distribution provisioning profile.
